services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:17.6
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=supersecret

  elixir-shell:
    image: elixir:1.18.4-alpine
    volumes:
      - ./app:/app
